# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nobel_prize_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nobel_prize_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19nobel_prize_service.proto\x12\x0bnobel_prize\"M\n\x13\x43\x61tegoryYearRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nstart_year\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_year\x18\x03 \x01(\x05\"$\n\x11MotivationRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"1\n\x0bNameRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"X\n\x15LaureateCountResponse\x12\x17\n\x0ftotal_laureates\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"q\n\x17LaureateDetailsResponse\x12.\n\tlaureates\x18\x01 \x03(\x0b\x32\x1b.nobel_prize.LaureateDetail\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"D\n\x0eLaureateDetail\x12\x0c\n\x04year\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\nmotivation\x18\x03 \x01(\t2\xa8\x02\n\x11NobelPrizeService\x12^\n\x16GetLaureatesByCategory\x12 .nobel_prize.CategoryYearRequest\x1a\".nobel_prize.LaureateCountResponse\x12^\n\x18GetLaureatesByMotivation\x12\x1e.nobel_prize.MotivationRequest\x1a\".nobel_prize.LaureateCountResponse\x12S\n\x11GetLaureateByName\x12\x18.nobel_prize.NameRequest\x1a$.nobel_prize.LaureateDetailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nobel_prize_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORYYEARREQUEST']._serialized_start=42
  _globals['_CATEGORYYEARREQUEST']._serialized_end=119
  _globals['_MOTIVATIONREQUEST']._serialized_start=121
  _globals['_MOTIVATIONREQUEST']._serialized_end=157
  _globals['_NAMEREQUEST']._serialized_start=159
  _globals['_NAMEREQUEST']._serialized_end=208
  _globals['_LAUREATECOUNTRESPONSE']._serialized_start=210
  _globals['_LAUREATECOUNTRESPONSE']._serialized_end=298
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_start=300
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_end=413
  _globals['_LAUREATEDETAIL']._serialized_start=415
  _globals['_LAUREATEDETAIL']._serialized_end=483
  _globals['_NOBELPRIZESERVICE']._serialized_start=486
  _globals['_NOBELPRIZESERVICE']._serialized_end=782
# @@protoc_insertion_point(module_scope)
