# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nobel_prize_service_pb2 as nobel__prize__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nobel_prize_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NobelPrizeServiceStub(object):
    """Service definition for Nobel Prize queries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLaureatesByCategory = channel.unary_unary(
                '/nobel_prize.NobelPrizeService/GetLaureatesByCategory',
                request_serializer=nobel__prize__service__pb2.CategoryYearRequest.SerializeToString,
                response_deserializer=nobel__prize__service__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.GetLaureatesByMotivation = channel.unary_unary(
                '/nobel_prize.NobelPrizeService/GetLaureatesByMotivation',
                request_serializer=nobel__prize__service__pb2.MotivationRequest.SerializeToString,
                response_deserializer=nobel__prize__service__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.GetLaureateByName = channel.unary_unary(
                '/nobel_prize.NobelPrizeService/GetLaureateByName',
                request_serializer=nobel__prize__service__pb2.NameRequest.SerializeToString,
                response_deserializer=nobel__prize__service__pb2.LaureateDetailsResponse.FromString,
                _registered_method=True)


class NobelPrizeServiceServicer(object):
    """Service definition for Nobel Prize queries
    """

    def GetLaureatesByCategory(self, request, context):
        """Query 1: Get total laureates by category and year range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureatesByMotivation(self, request, context):
        """Query 2: Get total laureates by motivation keyword  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureateByName(self, request, context):
        """Query 3: Get laureate details by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NobelPrizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLaureatesByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureatesByCategory,
                    request_deserializer=nobel__prize__service__pb2.CategoryYearRequest.FromString,
                    response_serializer=nobel__prize__service__pb2.LaureateCountResponse.SerializeToString,
            ),
            'GetLaureatesByMotivation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureatesByMotivation,
                    request_deserializer=nobel__prize__service__pb2.MotivationRequest.FromString,
                    response_serializer=nobel__prize__service__pb2.LaureateCountResponse.SerializeToString,
            ),
            'GetLaureateByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureateByName,
                    request_deserializer=nobel__prize__service__pb2.NameRequest.FromString,
                    response_serializer=nobel__prize__service__pb2.LaureateDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nobel_prize.NobelPrizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nobel_prize.NobelPrizeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NobelPrizeService(object):
    """Service definition for Nobel Prize queries
    """

    @staticmethod
    def GetLaureatesByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel_prize.NobelPrizeService/GetLaureatesByCategory',
            nobel__prize__service__pb2.CategoryYearRequest.SerializeToString,
            nobel__prize__service__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureatesByMotivation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel_prize.NobelPrizeService/GetLaureatesByMotivation',
            nobel__prize__service__pb2.MotivationRequest.SerializeToString,
            nobel__prize__service__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureateByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel_prize.NobelPrizeService/GetLaureateByName',
            nobel__prize__service__pb2.NameRequest.SerializeToString,
            nobel__prize__service__pb2.LaureateDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
